### ISSUE TITLE
[BUG] Extractor and GE giving different `datasource_url`s

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1195]
**Purpose:**
In Snowflake, at least, Great Expectations is returning a different datasource than the SnowflakeOperator's extractor is generating, causing two datasets to be created in the lineage UI, one from Snowflake, one from GE.

The GE dataset has a `datasource_url` like:
`snowflake://[account].us-east-1/BENJI.YELLOW_TRIPDATA`

while the Snowflake extractor's dataset has a `datasource_url` like:
`snowflake://[account]/SANDBOX.BENJI.YELLOW_TRIPDATA`

where the latter has the database as well as schema and table, and is missing the region found in GE's url.

**Proposed implementation**
Not sure. Probably just need to add a database option to the url string in the string builder.

**Comment by mobuchowski** [comment]
I think no-`us-east-1` is clearly a bug. There is one Snowflake AWS default region, and it's `us-west-1` (Oregon): https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#using-an-account-locator-as-an-identifier

`GE` one misses `.aws` I think too.

At the end, we'd prefer to have canonical - full-names, with region and cloud, since they are uniquely representing the dataset namespace.

**Comment by harels** [comment]
PR #1527
