### ISSUE TITLE
[INTEGRATION][dbt] The dbt integration extracts incomplete lineage when running single models one by one 

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#1438]
If I take an existing dbt project and run each model one by one using the `dbt run` command, I expect to see the same lineage than if running all models with one `dbt run` command.
However, running each model one by one produces incomplete lineage.
This happens for example in the Cosmos project that runs a dbt project as an Airflow dag: https://github.com/astronomer/astronomer-cosmos

**Comment by denimalpaca** [comment]
So the issue here is with `dbt` itself and the way its models look at datasets. Basically, every model can't "see" the datasets it uses as inputs, because it did not create them. So you have to use the [sources](https://docs.getdbt.com/docs/build/sources) jinja template in the `schema.yml` file _and_ the sql files the models use. This means we probably have to do some dynamic injection or something fancy to use those sources before the model is run.

Even when running the entire dbt model as one `dbt run`, the initial dataset(s) won't be shown.

This is also a bit different in the Astro Lineage UI and Marquez in how the datasets are displayed.

**Comment by jlaneve** [comment]
I wonder if the right solution here is to contribute the solution back to `dbt-ol`? Then, instead of injecting stuff into the code and letting `dbt-ol` pick it up as-is, we can move that injection logic into the actual tool that's parsing the code and emitting the events without injecting

**Comment by denimalpaca** [comment]
This may warrant a real conversation, but I do think this should live in `dbt-ol`, it's just a matter of how the `source` information gets passed / who we expect to be outlining that. If it's up to the user, if they want full lineage, they have to know to use `source` in certain places. That means if they're using something like Cosmos, they have to use `source` everywhere instead of `ref`, which is pattern breaking from what I understand. And there's no current way to override configs for `source` in memory, according to the dbt docs. Hence the conclusion that there may have to be injection to capture full lineage when the internal dbt dag is pulled apart.

**Comment by denimalpaca** [comment]
@mobuchowski it is the latter issue, that using the node selector doesn't catch input datasets, it seems. So I do agree this is a `dbt-ol` issue, what I am having trouble with is thinking what the appropriate solution is here. And the solution may be that this is an issue for the writer of the dbt models, who will be expected to use `source` instead of `ref`.

**Comment by mobuchowski** [comment]
For example, we might parse `ref` ourselves. I think we definitely should not force people to use dbt in a different way than they normally do. Using `source` inside of dbt graph is also probably a bug in usage - it's expected to refer to other dbt models using ref.

**Comment by denimalpaca** [comment]
I'm testing some of this more in-depth right now, so in an hour or so I'll have a better understanding of what is working and what does not.

**Comment by denimalpaca** [comment]
So this _does_ seem to be working when running models one by one, I just did this with Cosmos and `dbt-ol` with *just* the `dbt-ol run` command. `dbt-ol test`, I believe, is what is breaking the lineage graph, running on multiple models or a single one at a time.

**Comment by harels** [comment]
resolved by #1354
