### ISSUE TITLE
[GE/Common integration] GE unable to find the openlineage integration starting with 0.19.1

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/OpenLineage#1524]
Beginning with OpenLineage 0.19.1 , Great Expectations is seemingly unable to find the `openlineage.common.provider.great_expectations` module. 

`$ great_expectations checkpoint run <checkpoint>` throws the following error:

```
No module named `openlineage.common.provider.great_expectations` could be found in your plugins directory.
    - Please verify your plugins directory is configured correctly.
    - Please verify you have a module named `openlineage.common.provider.great_expectations` in your plugins directory.
```

When an earlier version of the integration is used, the command executes without the error being thrown.

**Comment by denimalpaca** [comment]
We investigated this issue and it is caused by a hidden new dependency: the Great Expectations integration, to run, now needs `openlineage-sql==0.19.2` installed. This may also be the case for other common providers.

Either these common providers _do_ need the SQL dependency, in which case a better error message is required, or they do not and this is a bug that is causing a breaking change.
