### ISSUE TITLE
[PROPOSAL] Support for Static lineage in the spec

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#1837]
**Purpose:**
Today OpenLineage captures metadata mainly in the context of a run that is actively accessing and modifying/producing data. The metadata collected covers both dynamic aspects that are specific to the run (how long it took, how many rows were produced, ...) and static metadata that does not change every time the job runs (inputs, outputs, dataset schema, code version, ...). 

We're referring to those two types of metadata as dynamic and static.

We want to collect that static metadata for `Datasets` and `Jobs` outside of the context of a run through OpenLineage. 
Examples:
 - defining dataset owners 
 - marking a dataset as containing personally identifying information.

**Proposed implementation**
The proposed implementation is to add two new types of events to the spec:
 - Job event: contains input datasets, output datasets, and job static facets.
 - Dataset events: contains static metadata dataset facets.

run.facets, dataset.inputFacets and  dataset.outputFacets are dynamic metadata about the specific run.
job.facets, dataset.facets are static metadata.

**Comment by julienledem** [comment]
Submitted: https://github.com/OpenLineage/OpenLineage/pull/1839

**Comment by henneberger** [comment]
I would suggest adding another timestamp field to static facets to allow for soft deletes.

Aren't some facets static by definition, do they need a new field to identify them? I would think this is the responsibility of the open lineage consumer implementation to process facets, rather than the job of the emitter to correctly identify what should be static.

What if emitters just emitted an 'OTHER' eventType for additional metadata tagging? The ol implementation can disregard it as part of the lineage DAG, since it has no START event. So the view would be that ol metadata maintainers are just another ol emitter. If they are only modifying datasets, their jobid could be the maintainers unique id as an origination identifier.
