### ISSUE TITLE
[PROPOSAL] Formalizing transformation types

### ISSUE THREAD

**Issue by jenspfaug** [OpenLineage/OpenLineage#2186]
**Purpose:**
Automatic support of lineage use cases highly depends on the type of transformations between columns. Oftentimes the use cases to be supported pose a significant risk (compliance, impact analysis) and false negatives are highly undesirable. This means that the taxonomy of transformation types supported by OpenLineage has to be tightly specified. Otherwise OpenLineage consumers cannot build reliable automation on top of the transformation types, and therefore not reliably support these high-risk use cases. This is a proposal for modifying the column-level lineage facet with a tightly specified taxonomy of transformation types.

**Proposed implementation**
1. Change transformationType definition:
From:
```
"transformationType": {
    "type": "string",
    "description": "IDENTITY|MASKED reflects a clearly defined behavior. IDENTITY: exact same as input; MASKED: no original data available (like a hash of PII for example)"
}
```

To:
```
"transformationType": {
    "description": "The type of the transformation. One of:
         IDENTITY: Any exact copy from source to target.
         TRANSFORMED: Any data transfer that is not an IDENTITY.
         INDIRECT: A lineage relationship that does not constitute any data transfer but a relationship that indirectly influences the movement of data. For example, this can be a join, group, filter, or order.
    ",
    "type": "string",
    "enum": ["IDENTITY", "TRANSFORMED", "INDIRECT"]
}
```

2. Add transformationSubType:
```
"transformationSubType": {
    "description": "A producer-specific subtype of the transformation type. One of FILTERING, GROUPING, ORDERING or user-specified."
    "type": "string",
}
```

There is more detail in the discussion doc: https://docs.google.com/document/d/1KgLQy5fibXdDF3k186BzFTgFYe81Yu3UyTDH9VBMmaA/edit?usp=sharing&resourcekey=0-Ng_0eR3Sv1fC880tvUsG5A

**Comment by pawel-big-lebowski** [comment]
@jenspfaug Thanks again for working on this topic.

We already have to fields `transformationDescription` +  `transformationType` and this proposal adds the third `transformationSubType`. Given the fact, that #2187 adds those three fields, instead of adding just one, we don't have to take care of backward compatibility as producers will need to modify their implementation anyway to support new transformation types. When doing it again from the scratch, I would recommend creating `Transformation` object instead of three `transformation` prefixed fields.

I understand that the notion of `masked` transformation can be ambiguous. For example, definition of masking PII may vary across countries, industry standards, etc. However, I still find it useful in many scenarios. It seems to be a common use case behind Openlineage in many organisations to track lineage for personal data. We should have a marker with a meaning that downstream datasets no longer contain personal data. It is useful to let producers manually use the marker to tell: _I know I am reading personal data, but my output field X no longer contains it._ 

This will also work for other sensitive data categories. No matter why was this field sensitive within the organisation, it is not in the downstream. Having `isMasked` property within `Transformation` object would solve this I believe.  

The other option, which I consider cleaner but requiring more effort, is the ability of tagging dataset fields and transformation object containing information about the removed tags. I see it more as a long term solution which can be implemented in next iterations.

**Comment by mobuchowski** [comment]
@pawel-big-lebowski @jenspfaug @julienledem do you think there is more discussion needed on this, or just implementation?

**Comment by pawel-big-lebowski** [comment]
@mobuchowski more discussion is needed. some feedback on the idea from my comment would be welcome.

**Comment by jenspfaug** [comment]
@pawel-big-lebowski your proposal makes sense to me:

- Introduce a Transformation object and encapsulate transformation related information there
- Add an isMasked field
