### ISSUE TITLE
[PROPOSAL] Add a Transport abstraction to the OpenLineage clients

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#269]
**Purpose:**
The goal is to facilitate sending OpenLineage events over various protocols. (HTTP, queues, ...) independently of the logic.
This can be configured directly in the client or in the `ProxyBackend`

**Proposed implementation**
Have a backend abstraction to send a `Lineage event`
```java
interface Backend {
  void send(LineageEvent event);
}
```
The Backend class is configured given a backend name (ex: http).
the default implementation sends the events over http.

**Comment by collado-mike** [comment]
I do prefer the abstraction `Transport`- the receiver may be a "backend" service, or it could be something like a PubSub or SQS queue.

**Comment by mobuchowski** [comment]
Same backend or transport should have same configuration between different language clients - same naming of env variables etc.

The backend, if not http, should be explicitely specified by some configuration variable.

**Comment by mobuchowski** [comment]
There are few issues with proposed interface regarding potential errors. 

1. Currently, integration default behavior with client is "fire and forget" - we don't want to cancel or interfere with underlying job even when client fails to send the event. Hovewer, this is not the case for client libraries. The underlying integration should be notified of failure to send event and decide how to react. This behavior is useful for example for logging. The client has no knowledge how integration is logging failures - however, Spark or Airflow know how underlying systems use logging.
2. Hovewer, different languages handle errors differently. Existing Java or Python implementations have no problems with current signature, since they usually communicate errors with exceptions. If we're going to do that, we should standarize this exception per language - to not make integration implementers guess whether they should catch some underlying libraries exception. Overthinking this, we might eventually have clients in languages that do not communicate errors via exceptions - but via some kind of `Result<T, E>` interface like Rust or error value like Go.
3. The implementations of `Transport` could use asynchronous semantics. In that case, we can't really notify integration with error value.

**Comment by collado-mike** [comment]
> * Overthinking this, we might eventually have clients in languages that do not communicate errors via exceptions - but via some kind of `Result<T, E>` interface like Rust or error value like Go.

Personally, I like the `Either` response pattern, but I don't think it's really idiomatic in Java or Python. I really like the pattern in Go, but most Java devs would look at it funny.

> * The implementations of `Transport` could use asynchronous semantics. In that case, we can't really notify integration with error value.

I think the `sendLineage` method's behavior should be synchronous. Otherwise, it's more difficult for integrations to react to failed calls. The underlying transport may be async, but we don't need to expose that to the caller. We can handle the Future internally and return once complete. If the integration environment prefers an async call, it should be up to the integration to manage how/when the new thread is fired off.
That said, if the language itself prefers async, I think it makes sense to write idiomatic code. E.g., a Javascript/Typescript impl should be `await` friendly.

**Comment by mobuchowski** [comment]
Created draft PR for Python: https://github.com/OpenLineage/OpenLineage/pull/329

**Comment by wslulciuc** [comment]
I'm a bit late to the discussion, but here are my thoughts / feedback! 😅

### Using **`Transport`** vs **`Backend`**

I agree with @collado-mike's suggestion on using `Transport` as the abstraction. I can see `HttpBackend`, `PubSub`, `Kafka`, etc all as possible transports (though the transport types can be broader or more specific). Of course, each `Transport` type would required specific configuration, and, based on the type, specific properties detailing the connection that could then be used to instantiate a `Transport` object: 

```java
Transport transport = new Transport.builder()
  .config(TransportConfig)
  .build();
transport.emit(RunEvent)
```

Note, I think the `Transport` should allow for types that are not yet supported, but may eventually be contributed to OpenLineage at some point in the future (though most transports should be covered) and should be considered in the overall design.

As for the configuration (=`TransportConfig`), this can be a simple `yml` (example below) or `json` file (and/or set via environment variables) with a minimal structure that allows the user to configure the transport:

```yaml
transport:
  - type:       # the transport type (ex: HttpBackend)
    url:        # url of backend with host and port
    timeout:    # timeout for all requests
    maxRetries: # max retries for all failed requests
   # ... more properties
```

### **`Transport`** interface

To be consistent with the OpenLineage clients (both `java` and `python`), I would continue to use the `emit()` method, rather than `send()` (effectively the same thing). Also, it might be helpful to have a method to emit more than just one event, or maybe just a single method that accepts `Set<RunEvent>`. But, what about partial emits? And, of course, ordering would matter here and might not provide much in terms of overall efficiency if events are still emitted sequentially.

```java
interface Transport {
  void emit(Set<RunEvent>);
}
```

> If the integration environment prefers an async call, it should be up to the integration to manage how/when the new thread is fired off.

@collado-mike, you're totally right, but we can make it clear by choosing good methods names on expected behavior (open for discussion, and mainly a suggestion):

```java
interface Transport {
  void emit(Set<RunEvent>);
  void emitAsync(Set<RunEvent>);
}
```

### **`Transport`** error handling

I see two options here, either 1) provide an option to the caller to handle errors via a class `EmitErrorHandler`, or 2) define a `EmitResult` class as suggested by @mobuchowski. Personally, I prefer the `EmitErrorHandler` as it leaves it up to the user on how the error should be handled while making error handling explicate:

```java
Transport transport = new Transport.builder()
  .config(TransportConfig)
  .registerErrorHandler(new EmitErrorHandler() {
    @Override
    public void handleError(Throwable throwable) {
      // Handle emit error here
    }
  }).build();
transport.emit(RunEvent)
```

If we went with `EmitResult` it could contain the set of events (or event) that failed to emit.

**Comment by mobuchowski** [comment]
@wslulciuc 

>TransportConfig

Yes, that's good idea - that's how I'd implement it in Java. Python, of course, might be more _dynamic_ 😉 

>Set<RunEvent>

I mean, batch endpoints make sense, but is there actual use case? :)
I'm not sure where we might want to emit relatively large amount of events at once. 
Additionally, his might require additional effort to implement on OpenLineage consumer side - would require additional HTTP endpoint. Also, something like Kafka already transparently does this in the background, with `batch.size` and `linger.ms`.

>emitAsync

I think forcing async by client is not something that we want to do "globally" as it's mostly particular integration's needs that force us into one or other direction. For example, new Airflow integration forces us to send events in another thread. In Java, I could imagine this could be something enabled when constructing client via builder rather than done by creating another method.

>Transport error handling

I would leave that to particular language's implementation. Your suggestion with `EmitErrorHandler` makes sense for Java, although I'd still prefer to have this particular discussion when implementing this on Java side.
