### ISSUE TITLE
[PROPOSAL] Cap the size of a serialized facet

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#402]
**Purpose:**
Some facets could get out of hand- e.g., the `UnknownEntryFacet` can sometimes serialize a class from Spark's LogicalPlan that will end up pulling in the classpath, the list of files read, or even the list of all functions defined in a catalog, such as Hive. A facet that's very large will cause some errors sending the payload (a separate issue that needs to be addressed).

Capping the size of any single facet will provide better quality of service for other facets that need to be reported and may currently be drowned out or omitted entirely due to unbounded facets.

**Comment by pawel-big-lebowski** [comment]
The issue is related to `UnknownEntryFacet` and there is no easy general solution to this, as `UnknownEntryFacet` concats JSON elements as string, and truncating it would break JSON syntax. 

The logs I saw were coming from a really simple job and the vast majority of event content was a documentation of available functions that were not even used within the job. They were coming from `functionRegistry` field in `SessionCatalog`(https://github.com/apache/spark/blob/v3.2.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/SessionCatalog.scala#L64)

To address this issue, we could start with Jackson property filter (as described here https://www.baeldung.com/jackson-serialize-field-custom-criteria) that removes at least this single field now and can be extended in the future.
