### ISSUE TITLE
[PROPOSAL] Modeling metadata update events

### ISSUE THREAD

**Issue by himgupta-ibm** [OpenLineage/OpenLineage#42]
**Purpose:**

Consider an event like owner_updated event - we will need to have the same asset as part of both inputs and outputs. This is because, this event takes an existing asset as input -- so this asset is part of input assets. Also, this event updates the metadata of the asset. In this sense, the event outputs a new state of the asset. So this asset is also part of output assets. 

We should discuss how best to go about representing such events in openlineage format.

**Comment by collado-mike** [comment]
To build on this, I wonder if a new API to push facets would allow for a lot more customization and flexibility in how job/dataset metadata can be updated. Job ownership is one example, but so are Job version information, such as source code location (which can be updated on deployment instead of publishing in the Run), Dataset metrics, such as quality checks or testing/validation metrics (which would be collected after the job run that writes a Dataset version), and Documentation (which probably doesn't need to be submitted by the Run).

I think the current intention is to post a `RunEvent` that contains all the necessary information and the service is responsible for determining how to version the jobs and datasets based on the facet values. That makes it difficult to post piecemeal components, such as in a job ownership change or a dataset validation job. Allowing explicit facet updates for job versions and dataset versions gives clients a lot more flexibility in constructing the lineage that makes sense for them.

**Comment by towhans** [comment]
+1 for updating job outside of a `RunEvent`. Graph of static lineage (as opposed to run level lineage) can be constructed from jobs and their input/output datasets alone.

**Comment by julienledem** [comment]
Based on the discussion, the description of the ticket needs to be updated. We need to track the owner of a Dataset, however  this is not what the `RunEvent` captures. `RunEvent` is for data modifications.
It would be great to have a separate proposal for tracking such changes.

**Comment by julienledem** [comment]
covered by https://github.com/OpenLineage/OpenLineage/issues/1837
