### ISSUE TITLE
[PROPOSAL][Spark] allow QueryPlanVisitors to know by which event they were triggered

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#484]
@collado-mike 's refactor of new extension model allows facet builders to react on only select events, such as `SparkListener*` events, RDDs and more. 

However, QueryPlanVisitors do not have that possibility. They are defined strictly for some `LogicalPlan`. In some cases, like `DatasetVersionDatasetFacet`, this matters. There needs to be different behavior for input and output datasets - which is already provided - and different behavior for particular moment in run, there expressed by `SparkListenerSQLExecutionStart` and `SparkListenerSQLExecutionStart` events. 

For input datasets, we need to be able to find the versions at start. If we did this additionally on end, then the possibly different version would override the first, proper one. 

Opposite reason is for output dataset. The dataset version on start would be misleading - only the version that is the result of job execution matters. 

So, how do we can solve this? 

One way would be to change signature of `QueryPlanVisitor`'s `isDefinedAt` and `apply` to accept some "runtime context" - different from current, immutable `OpenLineageContext`. Problem with that is that we'd break the interface that we just released. 

Another way would be to have "higher" interface that wraps `QueryPlanVisitor` and accepts this runtime context. We could have "wrapping visitor" for visitors that do not care about this concept at all, that would just extract current `LogicalPlan` and pass it to actual visitor.

Yet another way would be to forget about this "runtime context" idea, and add "current event" field to `OpenLineageContext`. The problem with that approach is that `OpenLineageContext` currently is immutable entity. Hovewer, it already assumes some of the fields are mutable, like visitor lists. 

I believe last option is the best - no breaking compatibility, way less glue code, just one question - can we break something by having mutable field inside? Isn't SparkListener's single thread guarantee enough?

**Comment by pawel-big-lebowski** [comment]
My first thought was to add `runContext` parameter to `apply` and `isDefinedAt` methods. We could provide within `QueryPlanVisitor` class  `default apply` and `default isDefinedAt`  methods that skips the extra 'runContext' parameter. This would give a possibility for some visitors to support `runContext`, while leaving other unaware of that. 

However, this approach is not doable without breaking the existing contracts as we rely now on `PartialFunction<LogicalPlan, List<Dataset>`. We would need change this into something like `PartialFunction<Tuple2<LogicalPlan, RunContext>, List<Dataset>` and this change should be spread all over the codebase including public builders and factories. 

That being said, I believe that extending `OpenLineageContext` is a way better approach to go and will try to go that way with a PoC.

**Comment by collado-mike** [comment]
There are a couple of ways to do this without breaking the existing contract. I don't really like that the `QueryPlanVisitor`s are a special case of the `AbstractInputDatasetBuilder`/`AbstractOutputDatasetBuilder` and are handled separately in the run builder. I refactored it that way because of how we collect information about the unvisited nodes. But I think if we can move those functions to simply be more specific versions of the *DatasetBuilders, we can simplify the run builder and make it easier to implement functions that apply to specific events. 

Some ways to do this could be wrapping the `QueryPlanVisitor`s in the `OpenLineageEventHandlerFactory` or we can add a new method directly to the `QueryPlanVisitor` class that restricts which events it applies to. For the wrapper option, an interface like the following would allow implementers the option to simply implement the interface and let the factory detect and invoke the transformation method
```java
public interface EventTriggeredQueryPlanVisitor<T extends SparkListenerEvent, D extends Dataset> {

  boolean matchesEvent(SparkListenerEvent event);

  default PartialFunction<SparkListenerEvent, List<D>> asListener() {
    QueryPlanVisitor<LogicalPlan, D> visitor = (QueryPlanVisitor<LogicalPlan, D>) this;
    return new AbstractPartialFunction<SparkListenerEvent, LogicalPlan>() {
      @Override
      public LogicalPlan apply(SparkListenerEvent x) {
        return visitor.context.getQueryExecution().get().optimizedPlan();
      }

      @Override
      public boolean isDefinedAt(SparkListenerEvent x) {
        return matchesEvent(x) && visitor.context.getQueryExecution().isPresent();
      }
    }.andThen(visitor.lift())
        .andThen(opt -> ScalaConversionUtils.asJavaOptional(opt)
            .orElse(Collections.emptyList()));
  }
}
```
`QueryPlanVisitor` implementations that implement this interface can define the `matchesEvent` method and the factory can filter them out and add them to the list of input/output dataset builders.

Alternatively, we could add a `matchesEvent` method to the `QueryPlanVisitor` class directly. The default implementation could match `SparkListenerSQLExecutionEnd` or `SparkListenerSQLExecutionStart`, while subclasses can override it to match one or the other. Then we can wrap all `QueryPlanVisitor`s with an implementation like the one above that applies the function to any `SparkListenerEvent` that matches the `QueryPlanVisitor`'s target event. This allows us to eliminate the distinction between `QueryPlanVisitor`s and the input/output Dataset builders entirely. 

I kind of think this latter approach is a better long term simplification. Thoughts?

**Comment by pawel-big-lebowski** [comment]
@collado-mike I was trying to figure out how to integrate `EventTriggeredQueryPlanVisitor` with the existing codebase which build an event, when something like this `https://github.com/pawel-big-lebowski/OpenLineage/pull/1/files` came to my mind. 

It's simple an it should solve the issue. Anything wrong with that?

**Comment by collado-mike** [comment]
Yeah, it's very simple - it's not entirely what I had in mind, but looking a bit deeper, what I had thought about is not as easy to implement as I first thought. For now, I think we should go with what you have. We can work on simplifying the input visitors/dataset builders distinction later.
