### ISSUE TITLE
[INTEGRATION][FLINK] Proposal doc for how metadata events are reported

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#596]
There has been a lot of discussion about how openlineage events should be reported for Flink jobs. For example, one option is to publish an event at the start of an application and then another at the end. Another option is to report any perceived structural changes (e.g., schema changes). Another is to report at every checkpoint.

We need a proposal doc that outlines different approaches and makes a single recommendation that can be approved by users. A flexible approach that allows consumers to pick and choose events they want to be notified of is an appealing approach, if possible.

**Comment by wjohnson** [comment]
I'm coming at this from a Spark angle so hopefully this still applies.  A few common use cases that I've seen include:

1. A fixed schema going to a fixed table - e.g. I'm streaming a financial transaction into a financial transaction delta table.
1. A mixed schema going to a mix of tables - e.g. I've got a json body column which explodes to the real payload and based on that payload I send the results to a different delta table for each microbatch.

The brute force approach that fits the above would be to send an event on every single microbatch.  However, that will become very chatty and very redundant.

Instead, I would want to see an event only on the **first time an input/output combination occurs** and additional events only for some **structural change like adding or removing columns** on input/output combinations that have been seen before.

For example:
* Streaming Job takes in a Kafka topic as a streaming source and outputs / inserts to a postgresql database.
  * input dataset is the kafka topic and output dataset is the postgresql database
  * The first operation fires off an event because the combination of input(s) namespace+name and output namespace+name has not been seen before
* A message from the kafka topic has an additional column not seen before
  * This would fire off a new event because the input(s) namespace+name and now *schema* do not match and known combination that has already passed through.

This way we minimize the traffic going to the service supporting the openlineage protocol. But we do increase the complexity by storing many different events and checking to see if they exist and have changed.

Maybe there's a time to live on that set of known events?  That way long-running Spark jobs can free up memory once in a while if a bunch of rare events occur and start hogging memory?
