### ISSUE TITLE
airflow: OPENLINEAGE_URL path is hardcoded

### ISSUE THREAD

**Issue by cerveada** [OpenLineage/OpenLineage#695]
It seems like `api/v1/lineage` is always appended to the `OPENLINEAGE_URL`. It would be useful to set this via some parameter.

**Comment by mobuchowski** [comment]
New HTTP transport config might be a good place to disable that behavior: https://github.com/OpenLineage/OpenLineage/tree/main/client/python#http

**Comment by parshnt** [comment]
@mobuchowski / @JDarDagran - Currently when we configure the Openlineage client installed on Airflow using env variables (OPENLINEAGE_URL and OPENLINEAGE_API_KEY). The `api/v1/lineage` is still appended to the URL.

this is because, by default, the endpoint gets added while creating HttpConfig. (https://github.com/OpenLineage/OpenLineage/blob/d5b7db1979039b29236a698844374dccde21442c/client/python/openlineage/client/transport/factory.py#L128)

can we make a change to set the endpoint as None (empty string) while creating the HttpConfig?
