### ISSUE TITLE
spark: Vulnerability `CVE-2018-1000873`

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#704]
The `openlineage-spark` lib currently has the vulnerability [`CVE-2018-1000873`](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1000873) which should be addressed:

<img width="522" alt="Screen Shot 2022-04-25 at 2 19 33 PM" src="https://user-images.githubusercontent.com/1553185/165176872-2a76c13c-9caa-4bbe-b72a-9d0a72ea7452.png">

**Comment by collado-mike** [comment]
The OpenLineag Spark library matches dependencies based on the version of that dependency in Spark. For Jackson, the Spark dependencies are below:

Spark 2.4.1 dependency - https://github.com/apache/spark/blob/v2.4.0/pom.xml#L161
Spark 3.0.0 dependency - https://github.com/apache/spark/blob/v3.0.0/pom.xml#L169

Based on the CVE, Spark 3.X is safe because it relies on a version of Jackson greater than `2.9.8`. However, the Spark 2.4.X branch depends on a vulnerable version of Jackson.

Note the description of the CVE - 

> Improper Input Validation vulnerability in Jackson-Modules-Java8 that can result in Causes a denial-of-service (DoS). This attack appear to be exploitable via The victim deserializes malicious input, specifically very large values in the nanoseconds field of a time value.

This describes a vulnerability that impacts services deserializing JSON input. The openlineage-spark library is never used to process request input, so it's really not vulnerable to attack. We can bump our dependency, but it would be for optics only. There's not much risk to doing so except for the possibility of using some Jackson API that isn't compatible with the version of the library found in Spark 2.4.x runtimes.

**Comment by pawel-big-lebowski** [comment]
Maven central says which jackson subpackage vulnerability responds to `[jackson-datatype-jsr310](https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310)` 
![image](https://user-images.githubusercontent.com/1646950/165757954-bd4550cc-27d2-4616-82da-58617df8dbc5.png)

Unfortunately, it is us who explicitly include this jar in runtime: 
https://github.com/OpenLineage/OpenLineage/blob/14e6768f180b238c48a8a3e2279e7c0f69aedca0/integration/spark/build.gradle#L74

@collado-mike According to this, Spark 3 cannot be conisdered safe, even though it uses safe Jackson on its own because we do inject the unsafe one. 

I did some minor `jackson-datatype-jsr310` datatype version change in PR #711 which made it work for Spark 3.x. Unfortunately I cannot see any easy solution to fix it for Spark 2. 

@howardyoo What if we stopped supporting Spark 2.x? 

Otherwise old Spark 2 dependency introduces a vulnerability issue for Spark 3 users.

**Comment by howardyoo** [comment]
> Maven central says which jackson subpackage vulnerability responds to `[jackson-datatype-jsr310](https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310)` ![image](https://user-images.githubusercontent.com/1646950/165757954-bd4550cc-27d2-4616-82da-58617df8dbc5.png)
> 
> Unfortunately, it is us who explicitly include this jar in runtime:
> 
> https://github.com/OpenLineage/OpenLineage/blob/14e6768f180b238c48a8a3e2279e7c0f69aedca0/integration/spark/build.gradle#L74
> 
> @collado-mike According to this, Spark 3 cannot be conisdered safe, even though it uses safe Jackson on its own because we do inject the unsafe one.
> 
> I did some minor `jackson-datatype-jsr310` datatype version change in PR #711 which made it work for Spark 3.x. Unfortunately I cannot see any easy solution to fix it for Spark 2.
> 
> @howardyoo What if we stopped supporting Spark 2.x?
> 
> Otherwise old Spark 2 dependency introduces a vulnerability issue for Spark 3 users.

Can you elaborate more on why you `cannot see any easy solution to fix for Spark 2` to resolve this vulnerability? I believe we do ship the Jackson library within our package according to the version (the 'unsafe version') that we inject, and I believe you have tried that route for Spark 3.x successfully. However, not sure exactly what kind of problems you had to deal with when you tried that with Spark 2.

I do agree with @collado-mike 's comment :
```
This describes a vulnerability that impacts services deserializing JSON input. The openlineage-spark library is never used to process request input, so it's really not vulnerable to attack. We can bump our dependency, but it would be for optics only. There's not much risk to doing so except for the possibility of using some Jackson API that isn't compatible with the version of the library found in Spark 2.4.x runtimes.
```
So, I'd like to understand more details on it.

**Comment by pawel-big-lebowski** [comment]
It is us who include `jackson-datatype-jsr310` jar which contains the vulnerability and we can specify which version shall be included. `jackson-datatype-jsr310` works only where other jackson packages are avaialable on the classpath and they are loaded to classpath with standard Spark library. However, the version of `jackson-datatype-jsr310` has to be compatible with jackson library. 

The problem is that we're building a single JAR that has to work with both Spark 2.x and Spark 3.x. If we use old version of `jackson-datatype-jsr310` (like we do now), we introduce CVE-2018-1000873 to Spark 3 users. But, if we upgrade `jackson-datatype-jsr310`, we're losing compatibility with the old Jackson available in Spark 2.x and Spark 2.x integration stops working. 

The easiest way to solve this is to stop Spark 2.x version support and upgrade `jackson-datatype-jsr310` jar. Another perhaps-possible way is to include by us shaded jackson jars (jackson visible only to our implementation) but this can make our spark-openlineage jar pretty heavy. We could also try replace jackson with something else (like gson). 

I also agree with @collado-mike's comment:

> This describes a vulnerability that impacts services deserializing JSON input. The openlineage-spark library is never used to process request input, so it's really not vulnerable to attack.

However, this can discourage our users. Most of the users are not able to verify the way we're using vulnerable libraries, and assess the risk on their own.

**Comment by howardyoo** [comment]
Ok, due to the vulnerability that may pose greater issue in the future, I also agree that going forward with Spark 3.x and stop supporting Spark 2.x will be the way to go. I assume due to this vulnerability existing spark 2.x users would probably upgrade their sparks to 3.x, so let's go ahead and desupport spark v2.x support, unless there is any objections posted in this thread.

**Comment by howardyoo** [comment]
I would say we could announce the desupport of Spark v2.x in our website - but before doing that perhaps we should announce it to let the users have ample time to start upgrading and testing their existing Spark 2.x to 3.x - so tentative timeline could be to announce it sometime in May of 2022 - and then eventually desupport it by end of June, 2022.

**Comment by pawel-big-lebowski** [comment]
the issue is no longer present for latest releases.

![image](https://github.com/OpenLineage/OpenLineage/assets/1646950/4f6b4baf-c139-4501-a18e-21f8b087a99c)
