### ISSUE TITLE
spec: job facet for describing job (e.g. task in airflow) types

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#812]
### Problem Statement
Currently, OpenLineage specification does not have a dedicated FACET under JOB to describe what type (kind?) of job is it categorized into. For AIRFLOW integration, a job is a TASK instance, and task instances are generally associated with the `type` of `operators` such as DAG, Task, Spark, DBT, snowflake, postgreSQL, etc.

### Proposed solution
Add a new facet : `type` that may describe the `type` of the job such as:
```
  "job": {
    "facets": {
      "type": {
        "name": "Spark"
      }
   ....
}
```
- The type can be the enumeration of the following values, but not limited to:
  - Airflow DAG
  - Airflow Task
  - Spark
  - DBT Model
  - Snowflake Query

The concept is that this type value can be useful for backends like Marquez to detect and display a specific types of the job accordingly.

**Comment by mobuchowski** [comment]
I would refrain from having some closed enumeration of a possible values, since the possibilities here are endless and mutable, and rather a set of fields that describe particular properties of a job. The big question here is what can and should we model as a job.

Generally, job describes some processing of data: they have inputs and outputs, all are optional - some jobs produce data, some jobs consume data, some jobs transform data. Job that neither consumes nor produces data isn't very useful for data lineage - but it can be useful for job lineage, for example modeling Airflow's DAG run itself encompassing runs of particular tasks is useful if we want to group those tasks. So, one general category that comes to mind is whether the job is processing data itself, or just scheduling other tasks - are there jobs that do both?

Jobs usually aren't magic devices - they happen "as part of" or utilizing some data processing system. One field could describe what actually the system is. 

Another generic piece of information is "mode" in which the data is processed. Two categories jump into mind - batch and streaming. We can have batch and streaming specific facets.

But is that all? Maybe we _could_ model end consumers of a datasets - dashboards, ML models, KPIs as a jobs - somewhat similar to what [dbt exposures](https://docs.getdbt.com/docs/building-a-dbt-project/exposures) do. The same could be done with sources - we could model backend applications as jobs, or ETLs that gather this data, or both... 

But it's not clear that we _should_ model them as a job. Maybe we're only interested in sources as abstract dataset that ETLs pull from, and stuff like dashboards could be represented as just an output dataset.

**Comment by howardyoo** [comment]
> 

sure, I will update the description to not express it as 'enumeration', freeform text would be more ideal.
Perhaps, this should be considered as identical to #989 , since it looks like that issue is essentially trying to do the same thing.

I will close this issue off as duplicate. Thanks!

**Comment by mobuchowski** [comment]
Will copy my comment there then
