### ISSUE TITLE
airflow: Airflow Example Dag Tasks can not collect lineage

### ISSUE THREAD

**Issue by cdmikechen** [OpenLineage/OpenLineage#817]
I have asked a similar question on slack, but I haven't received a reply. So I create this again in the issue, hoping to get a confirmation.

I am now running airflow 2.3.1 and have started a latest marquez service by docker-compose. I found that using the example DAG of airflow can only see the job information, but not the lineage of the job. 
How can I configure it to see the lineage? 

![image](https://user-images.githubusercontent.com/12069428/171556218-ef8e77eb-7476-4a2f-91cc-f0fb07b6df08.png)
![image](https://user-images.githubusercontent.com/12069428/171556257-447c2cc8-5520-4cc1-8780-ef445345636d.png)

Today, I checked the openlineage events, I found that `inputs` is empty. Is this the reason why I can't see lineage?
```json
{
  "eventTime": "2022-06-01T09:32:42.868914Z",
  "eventType": "COMPLETE",
  "inputs": [],
  "job": {
    "facets": {
      "sourceCode": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.8.2/integration/airflow",
        "_schemaURL": "https://raw.githubusercontent.com/OpenLineage/OpenLineage/main/spec/OpenLineage.json#/definitions/SourceCodeJobFacet",
        "language": "python",
        "source": "    def load(**kwargs):\n        ti = kwargs['ti']\n        total_value_string = ti.xcom_pull(task_ids='transform', key='total_order_value')\n        total_order_value = json.loads(total_value_string)\n\n        print(total_order_value)\n"
      }
    },
    "name": "tutorial_etl_dag.load",
    "namespace": "dev"
  },
  "outputs": [],
  "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.8.2/integration/airflow",
  "run": {
    "facets": {
      "unknownSourceAttribute": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.8.2/integration/airflow",
        "_schemaURL": "https://raw.githubusercontent.com/OpenLineage/OpenLineage/main/spec/OpenLineage.json#/definitions/BaseFacet",
        "unknownItems": [
          {
            "name": "PythonOperator",
            "properties": {
              "_BaseOperator__from_mapped": false,
              "_BaseOperator__init_kwargs": {
                "python_callable": "<<non-serializable: function>>",
                "retries": 2,
                "task_id": "load"
              },
              "_BaseOperator__instantiated": true,
              "_dag": "<<non-serializable: DAG>>",
              "_inlets": [],
              "_log": "<<non-serializable: Logger>>",
              "_outlets": [],
              "depends_on_past": false,
              "do_xcom_push": true,
              "doc_md": "#### Load task\nA simple Load task which takes in the result of the Transform task, by reading it\nfrom xcom and instead of saving it to end user review, just prints it out.\n",
              "downstream_task_ids": [],
              "email_on_failure": true,
              "email_on_retry": true,
              "executor_config": {},
              "ignore_first_depends_on_past": true,
              "inlets": [],
              "op_args": [],
              "op_kwargs": {},
              "outlets": [],
              "owner": "Airflow",
              "params": "<<non-serializable: ParamsDict>>",
              "pool": "default_pool",
              "pool_slots": 1,
              "priority_weight": 1,
              "python_callable": "<<non-serializable: function>>",
              "queue": "default",
              "retries": 2,
              "retry_delay": "<<non-serializable: timedelta>>",
              "retry_exponential_backoff": false,
              "show_return_value_in_logs": true,
              "start_date": "<<non-serializable: DateTime>>",
              "task_group": "<<non-serializable: weakproxy>>",
              "task_id": "load",
              "trigger_rule": "all_success",
              "upstream_task_ids": [
                "transform"
              ],
              "wait_for_downstream": false,
              "weight_rule": "downstream"
            },
            "type": "operator"
          }
        ]
      }
    },
    "runId": "8043a227-243f-4531-bb1d-8511895e8b6e"
  }
}
```

**Comment by howardyoo** [comment]
The 'lineage' in Marquez require DataSets (whether it be input or output) and that is what connects these 'jobs' (Tasks in airflow).

PythonOperator does not have a generic means to product input/output datasets like for example, PostgreSQL operator does, so that's why you won't see the multiple jobs as they would be considered 'separate'

**Comment by cdmikechen** [comment]
@howardyoo 
Hi~
I think if we only see dataset lineages, Marquez/Openlineage will bring very limited help to users in business / data governance. Most of the time, our demand for data governance and datasets are closely linked. Users should be able to view the relationships between different data entities from multiple dimensions.

**Comment by howardyoo** [comment]
> @howardyoo Hi~ I think if we only see dataset lineages, Marquez/Openlineage will bring very limited help to users in business / data governance. Most of the time, our demand for data governance and datasets are closely linked. Users should be able to view the relationships between different data entities from multiple dimensions. For example, I can define multiple levels of entities in atlas to represent the refined management of the business.

Yes, I understand. We are currently working on to have other operators like python and bash (which are some of the most popular operators in airflow) to have more metadata in terms of workflows.

There is also a roadmap to support Parent - child relationships between DAG runs and Task instances so that workflows independent on the dataset can also be stored and visualized on top of Marquez (and Astro). OpenLineage/Marquez may not be on par with what Atlas currently provides, but it is fast growing project, and certainly has a bright future ahead!

**Comment by collado-mike** [comment]
Hi @cdmikechen. The issue with the PythonOperator is that we cannot scan arbitrary python code to determine input and output datasets. The source code of a PythonOperator can do anything - read from a file on disk using pandas, execute a SQL query, make an API call (as you're doing with XCOM)... And of course, users can build up the data sources dynamically, so that scanning the code would give us no insight and we'd have to actually execute the code in order to determine the datasets being read/written.

We hope to have an API for PythonOperator users to manually publish the input/output datasets, though, to be frank, we'd prefer users move to more declarative APIs, like [taskflow](https://airflow.apache.org/docs/apache-airflow/stable/concepts/taskflow.html), which allows lineage to be collected without custom code in the users' DAGs. In the meantime, you can definitely write some custom code to publish lineage events. Let me know if you're interested in pursuing that route and I can help point you in the right direction. It would be nice to even make up a document for other users with steps to follow and some example code.

**Comment by cliffordEmmanuel** [comment]
> There is also a roadmap to support Parent - child relationships between DAG runs and Task instances so that workflows independent on the dataset can also be stored and visualized on top of Marquez (and Astro). OpenLineage/Marquez may not be on par with what Atlas currently provides, but it is fast growing project, and certainly has a bright future ahead!

Hi @howardyoo, concerning the roadmap to support Parent - child relationships between the DAG runs and Task instances, is there any progress, or could you point in the right direction?

Thanks.

**Comment by cliffordEmmanuel** [comment]
> We hope to have an API for PythonOperator users to manually publish the input/output datasets, though, to be frank, we'd prefer users move to more declarative APIs, like [taskflow](https://airflow.apache.org/docs/apache-airflow/stable/concepts/taskflow.html), which allows lineage to be collected without custom code in the users' DAGs. In the meantime, you can definitely write some custom code to publish lineage events. Let me know if you're interested in pursuing that route and I can help point you in the right direction. It would be nice to even make up a document for other users with steps to follow and some example code.

Hi @collado-mike, i'm interested in writing custom code to publish lineage events, i'd be grateful if you could point me in the right direction.

Thanks.

**Comment by erikalfthan** [comment]
An idea for inputs and outputs  is to use the dataset inlets and outlets from the operator. The dataset uri should be a good identifier.

Sure, the python operator can do anything, but if you build on the airflow concept of datasets, it should be consistent and perhaps possible to make generic for more than just the python operator/extractor.
