### ISSUE TITLE
Finalize the OpenLineage mission statement

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#84]
The mission statement is part of our technical charter.
We started from: 

> "The mission of the Project is to enable the industry at-large to collect lineage metadata consistently and comprehensively across complex pipelines, creating a deeper understanding of data."

We'd want to capture that this is specifically operational lineage, or lineage and metadata collected as the job is running. It is also something more widely applicable than just data pipelines, and should reflect that.

The current proposal is: 

> "The mission of the Project is to enable the industry at-large to collect real-time lineage metadata consistently across complex ecosystems, creating a deeper understanding of how data is produced and used"

**Comment by rossturk** [comment]
How about: "to enable the industry at-large to collect real-time lineage metadata consistently across complex ecosystems, creating a deeper understanding of how data is produced and used"

Since the addition of "real-time" makes the sentence really complex, I looked for opportunities to reduce and figured that "and comprehensively" was nice but not necessary.

Thoughts?

**Comment by julienledem** [comment]
That makes sense to me. I like it.

**Comment by wslulciuc** [comment]
Mission statement is 🔥, @julienledem! My only suggestion would be:

> ... _produced and ~used~ consumed._

Otherwise 👍

**Comment by julienledem** [comment]
With 6 votes, the new mission is "The mission of the Project is to enable the industry at-large to collect real-time lineage metadata consistently across complex ecosystems, creating a deeper understanding of how data is produced and used"
