### ISSUE TITLE
Create generic facet to indicate job type and version info

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#989]
Both [Airflow](https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/openlineage/airflow/facets.py#L14-L25) and [Spark](https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/shared/facets/spark/v1/version-facet.json) have facets reporting information about the runtime engine executing the job. We should create a generic facet that can report information about the processing engine so that OpenLineage consumers can see information about the runtime without needing to check for engine-specific facets. E.g., consider the following run facet

```json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$id" : "https://openlineage.io/spec/facets/1-0-0/ProcessingEngineVersionRunFacet.json",
  "$defs" : {
    "ProcessingEngineVersionRunFacet" : {
      "allOf" : [ {
        "$ref" : "https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet"
      }, {
        "type" : "object",
        "properties" : {
          "name" : {
            "description" : "The name of the job execution engine",
            "type" : "string",
            "example" : "ApacheSpark"
          },
          "version" : {
            "description" : "The version of the processing engine.",
            "type" : "string",
            "example" : "3.2.1"
          }
        },
        "required" : [ "name" ]
      } ],
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "processingEngine" : {
      "$ref" : "#/$defs/ProcessingEngineVersionRunFacet"
    }
  }
}
```

**Comment by howardyoo** [comment]
> Hey @collado-mike - we definitely need to do that, but I think the scope around it is larger than that. I've commented on similar issue here: [#812 (comment)](https://github.com/OpenLineage/OpenLineage/issues/812#issuecomment-1205337556)

#812 is trying to do the same thing as this issue, so closing off as duplicate.

**Comment by mobuchowski** [comment]
Copied comment from #812:

I would refrain from having some closed enumeration of a possible values, since the possibilities here are endless and mutable, and rather have a set of fields that describe particular properties of a job. The big question here is what can and should we model as a job.

Generally, job describes some processing of data: they have inputs and outputs, all are optional - some jobs produce data, some jobs consume data, some jobs transform data. Job that neither consumes nor produces data isn't very useful for data lineage - but it can be useful for job lineage, for example modeling Airflow's DAG run itself encompassing runs of particular tasks is useful if we want to group those tasks. So, one general category that comes to mind is whether the job is processing data itself, or just scheduling other tasks - are there jobs that do both?

Jobs usually aren't magic devices - they happen "as part of" or utilizing some data processing system. One field could describe what actually the system is.

Another generic piece of information is "mode" in which the data is processed. Two categories jump into mind - batch and streaming. We can have batch and streaming specific facets.

But are those all processing categories that we could cover? Maybe we could model end consumers of a datasets - dashboards, ML models, KPIs as a jobs - somewhat similar to what [dbt exposures](https://docs.getdbt.com/docs/building-a-dbt-project/exposures) do. The same could be done with sources - we could model backend applications as jobs, or ETLs that gather this data, or both...

But it's not clear that we should model them as a job. Maybe we're only interested in sources as abstract dataset that ETLs pull from, and stuff like dashboards could be represented as just an output dataset.

At the end, there is one more question: should we keep all this information in one facet, or "spread it out" over several ones like https://github.com/OpenLineage/OpenLineage/issues/989

**Comment by howardyoo** [comment]
I do not see too much of an issue or obscurity of putting more description about jobs under the job's facets. Currently a job has name and namespace, and it is natural for job facets to also contain more specifics about a job, such as what type of technology (e.g. spark, airflow, db, snowflake, etc.) this job is going to be executed against, regardless of what the intention or the behavior of the job. This would give more context to enrich how jobs are described via openlineage.

As for the `mode`, I think it should rather be as part of the run facets, if we want to describe it, rather than as part of the job, since batch and streaming could be characteristics of 'runtime' rather than what the job is intending to do. Also, there is a possibility that the same job can either be deployed via streaming or batch, so that makes it more suitable to be located as  part of the 'run' facet.

**Comment by mobuchowski** [comment]
>I do not see too much of an issue or obscurity of putting more description about jobs under the job's facets. Currently a job has name and namespace, and it is natural for job facets to also contain more specifics about a job, such as what type of technology (e.g. spark, airflow, db, snowflake, etc.), or platform this job is going to be executed against (along with things like version of it), regardless of what the intention or the behavior of the job. This would give more context to enrich how jobs are described via openlineage.

👍 

>Also, there is a possibility that the same job can either be deployed via streaming or batch

@howardyoo I think that actually happens very rarely - only one system that I know of - Apache Flink - allows you to execute exactly the same code as both batch and streaming pipeline, and the responsibilities are usually very different - for example, backfilling as part of deploying upgraded job.
